function Genip() {     
    const path = require('path');
    this.genUrl="/settings/general"
    this.compid="SSI"
    this.compid1="SI"
    this.orginalCompid="MBM"
    this.mail="preetha@apptino.com"
    this.mail1="zen@gmail.com"
    this.invalidmail="adtional setting"
    this.orginalMail="admin@apptino.com"
    this.code ="AMD"
    this.code1="CHF"
    this.Name="Doller"
    this.code1="ZAR"
    this.factor ="0.16"
    this.symbol="AMD ֏"
    this.symbol1="CHF Fr"
    this.format="1 999,99"
    this.editcode="GBP"
    this.editcode1="CHF"
    this.editsymbol="GBP £"
    this.editfactor="0.001"
    this.editformat="1,999.999"
    this.roundOff="2"
    this.originalroundOff="1"
    this.date='2022/'
    this.orginaldate='1/'
    this.time="12"
    this.originaltime="24"
    this.timezone="(GMT+04:00) Ye"
    this.orginaltimezone="chennai"
    this.alert="Changes saved successfully"
    this.alreadyExisitsAlert="Currency code already exist"
    this.errorCodeMsg='Currency code required'
    this.errorNamemsg='Name required'
    this.errormsgSymbol='Required'
    this.errormsgFactor='Conversion factor required'
    this.errormsgCompIdenti='Company Identifier required'
    this.errormsgMail='Email required'
    this.errormsgRoundoff='Round off required'
    this.mappedDeleteAlert="Currency mapped with company cannot be deleted"
    this.errormsgInvalidmail="Invalid email"

}
module.exports = new Genip();